[interval]
post_ttl = 604800
fetch_interval = 60
post_interval = 60

[redis]
url = "redis://localhost:6379/0"

[twitter]
consumer_key = ""
consumer_secret = ""
token = ""
secret = ""

[mastodon]
instance_url = "https://mastodon.social"
access_token = ""

[bluesky]
host = "https://bsky.social"
identifier = "<handle>.bsky.social"
password = ""

[denylist]
names = []
authors = []
descriptions = []
