on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - run: docker buildx build --platform linux/amd64,linux/arm64/v8 .
      - if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build --platform linux/amd64,linux/arm64/v8 . -t ghcr.io/pbzweihander/rust-trending:${{ github.sha }} --push
          docker buildx build --platform linux/amd64,linux/arm64/v8 . -t ghcr.io/pbzweihander/rust-trending:latest --push

